# Generated by Django 3.0.7 on 2020-06-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='client_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
